apiVersion: apps/v1
kind: Deployment
metadata:
  name: txn-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: txn-service
  template:
    metadata:
      labels:
        app: txn-service
    spec:
      containers:
        - name: txn-service
          image: gnanendhar8/txn-service:latest
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: txn-service
spec:
  type: NodePort
  selector:
    app: txn-service
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081